# Generated by Django 4.2.7 on 2025-06-26 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_award_short_description_alter_award_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvrequest',
            name='user',
        ),
        migrations.AddField(
            model_name='cvrequest',
            name='email',
            field=models.EmailField(default='no-email@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvrequest',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvrequest',
            name='surname',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvsubmission',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cv.cvrequest'),
        ),
    ]
