# Generated by Django 4.2.7 on 2025-07-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_remove_cvrequest_user_cvrequest_email_cvrequest_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cvsubmission',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='cvsubmission',
            name='request',
        ),
        migrations.AddField(
            model_name='cvsubmission',
            name='email',
            field=models.EmailField(default='temp@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvsubmission',
            name='major',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cvsubmission',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cvsubmission',
            name='surname',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cvsubmission',
            name='status',
            field=models.CharField(default='processed', max_length=20),
        ),
        migrations.DeleteModel(
            name='CVRequest',
        ),
    ]
